version: "3.8"

services:
  
  cloud-vision:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080" 
    environment:
      - PORT=8080 
    container_name: cloud-vision-container
    restart: unless-stopped 
